name       : fuse
version    : 2.9.5
release    : 5
source     :
    - https://github.com/libfuse/libfuse/releases/download/fuse_2_9_5/fuse-2.9.5.tar.gz : 579f371cc5ffc1afca7057512bf7d52988a9ede57859a7c55e5b9f72435cdbb5
license    : LGPL-2.0
summary    : File Systems in User Space
description: |
    File Systems in User Space
builddeps  :
setup      : |
    sed -i 's|mknod|echo Disabled: mknod |g' util/Makefile.in
    %patch -p1 < $pkgfiles/0001-fusermount-Support-a-stateless-configuration.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/dev
    
    install -D -m 0644 $pkgfiles/fuse.conf $installdir/usr/share/defaults/fuse/fuse.conf
    rm -rfv $installdir/etc/
