name       : fuse
version    : 2.9.9
release    : 13
source     :
    - https://github.com/libfuse/libfuse/releases/download/fuse-2.9.9/fuse-2.9.9.tar.gz : d0e69d5d608cc22ff4843791ad097f554dd32540ddc9bed7638cc6fea7c1b4b5
license    : LGPL-2.0
summary    : File Systems in User Space
component  : system.utils
description: |
    File Systems in User Space
setup      : |
    sed -i 's|mknod|echo Disabled: mknod |g' util/Makefile.in
    %patch -p1 < $pkgfiles/0001-fusermount-Support-a-stateless-configuration.patch
    UDEV_RULES_PATH=%libdir%/udev/rules.d %configure --disable-static --enable-util
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/dev

    install -D -m 0644 $pkgfiles/fuse.conf $installdir/usr/share/defaults/fuse/fuse.conf
    rm -rfv $installdir/etc/
