name       : fuse
version    : 3.10.5
release    : 16
source     :
    - https://github.com/libfuse/libfuse/releases/download/fuse-3.10.5/fuse-3.10.5.tar.xz : b2e283485d47404ac896dd0bb7f7ba81e1470838e677e45f659804c3a3b69666
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : system.utils
summary    : File Systems in User Space
description: |
    File Systems in User Space
builddeps  :
    - libiconv-devel
patterns   :
    - common :
        - /usr/share/defaults/fuse
rundeps    :
    - fuse-common
setup      : |
    %patch -p1 < $pkgfiles/0001-fusermount-Support-a-stateless-configuration.patch
    %meson_configure \
        -Dudevrulesdir=/usr/lib64/udev/rules.d
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm0644 $pkgfiles/fuse.conf $installdir/usr/share/defaults/fuse/fuse.conf
    rm -rf $installdir/etc
    rm -rf $installdir/dev
